Makeup layout
JularJular/admin-panel-makeup pull request #2
Opened 2022-01-29 20:21 UTC by JularJular

2022-02-01 19:30 UTC, Muslik requested changes
Нужны доработки

2022-02-01 19:30 UTC, Muslik commented on index.html
> +    <div class="console">
Что такое console? Класс никак не обозначает контент который в нем лежит

2022-02-01 19:30 UTC, Muslik commented on index.html
> +          <input class="input search__input" type="text" value="" />
Это не input-ы и button-ы. Это все обычные div-ы

2022-02-01 19:30 UTC, Muslik commented on index.html
> +      <div class="console-table">
Просто table, table__header и тд

2022-02-01 19:30 UTC, Muslik commented on index.html
> +        <button class="button status-button"></button>
Почему два класса блока? Не по БЭМ

2022-02-01 19:30 UTC, Muslik commented on index.html
> +<html lang="en">
Не должно быть margin у каждого блока. Сделайте один padding (сверху, слева, справа) для всей страницы.

Высота header, footer в таблице не соответствуют макету. border задавайте в пикселях. 0.1rem это не то.

2022-02-03 14:43 UTC, JularJular commented on index.html
> +    <div class="console">
Переименовала в wrapper

2022-02-03 14:44 UTC, JularJular commented on index.html
> +          <input class="input search__input" type="text" value="" />
Сначала дивы так и были. Зачем-то потом переделала. Теперь все вернула зазад.

2022-02-03 14:44 UTC, JularJular commented on index.html
> +      <div class="console-table">
Приняно

2022-02-03 15:25 UTC, JularJular commented on index.html
> +<html lang="en">
Поправила

2022-02-04 22:28 UTC, Muslik approved these changes
Good

2022-02-07 15:34 UTC, merged